name: "Publish"

inputs:
  prettier_version:
    description: 'The version of prettier'
    required: true
    type: string
  tool_version:
    description: 'The version of the dotnet tool'
    required: true
    type: string
  commit:
    description: 'The commit of this version'
    required: true
    type: string
  nuget_api_key:
    description: 'The api key of the nuget repository'
    required: true
    type: string
  release_notes:
    description: 'The release notes'
    required: true
    type: string
  tag_name:
    description: 'The release notes'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: |
              6.0.x
              7.0.x
          include-prerelease: false
    - name: Pack prettier
      run: ./pack.sh "${{ inputs.prettier_version }}"
      shell: bash
    - name: Bundle
      run: ./bundle.sh "${{ inputs.tool_version }}"
      shell: bash
    - name: Attach nuget packages to Github releases
      uses: softprops/action-gh-release@v1
      with:
          files: "./nupkg/*.nupkg"
          body: "${{ inputs.release_notes }}"
          name: "${{ inputs.tool_version }} (prettier: ${{ inputs.prettier_version }})"
          tag_name: "${{ inputs.tag_name }}"
          target_commitish: "${{ inputs.commit }}"
          prerelease: ${{ contains(inputs.tool_version, '-') }}
    - name: Push packages to Nuget registry
      shell: bash
      run: dotnet nuget push ./nupkg/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "$NUGET_API_KEY" --skip-duplicate --no-symbols
      env:
          NUGET_API_KEY: "${{ inputs.nuget_api_key }}"
