name: "Manual publish"

on:
  workflow_dispatch:
    inputs:
      PRETTIER_VERSION:
        description: 'Prettier version'
        required: true 
        type: string
      TOOL_VERSION:
        description: 'Dotnet tool version'
        required: true 
        type: string
      TOOL_VERSION_SUFFIX:
        description: 'Suffix of the dotnet tool version. Including dash (-)!'
        required: false 
        type: string
        default: ''
      TAG_NAME:
        description: 'Name of the non-existing tag which will be created and then used for the release'
        required: true 
        type: string

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: ./.github/actions/publish
              with:
                prettier_version: "${{ inputs.PRETTIER_VERSION }}"
                tool_version: "${{ inputs.TOOL_VERSION }}.${{ github.run_number }}${{ inputs.TOOL_VERSION_SUFFIX }}"
                commit: "${{ github.sha }}"
                build_number: "${{ github.run_number }}"
                nuget_api_key: "${{ secrets.NUGET_API_KEY }}"
                release_notes: "${{ steps.github_release.outputs.changelog }}"
                tag_name: "${{ inputs.TAG_NAME }}"
