name: "Manual publish"

on:
    workflow_dispatch:
        inputs:
            PRETTIER_VERSION:
                description: "Prettier version"
                required: true
                type: string
            TAG_NAME:
                description: "Name of the non-existing tag which will be created and then used for the release"
                required: true
                type: string

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - name: Pack prettier
              run: ./pack.sh "${{ inputs.PRETTIER_VERSION }}"
              shell: bash
            - uses: actions/upload-artifact@v4
              with:
                  name: binary-linux
                  path: packed/linux-x64/prettier
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - name: Pack prettier
              run: ./pack.sh "${{ inputs.PRETTIER_VERSION }}"
              shell: bash
            - uses: actions/upload-artifact@v4
              with:
                  name: binary-windows
                  path: packed/win-x64/prettier.exe
    publish:
        runs-on: ubuntu-latest
        needs:
            - build-linux
            - build-windows
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: binary-windows
                  path: packed/win-x64/
            - uses: actions/download-artifact@v4
              with:
                  name: binary-linux
                  path: packed/linux-x64/
            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: ./.github/actions/publish
              with:
                  version: "${{ inputs.PRETTIER_VERSION }}"
                  commit: "${{ github.sha }}"
                  build_number: "${{ github.run_number }}"
                  nuget_api_key: "${{ secrets.NUGET_API_KEY }}"
                  release_notes: "${{ steps.github_release.outputs.changelog }}"
                  tag_name: "${{ inputs.TAG_NAME }}"
