name: "On prettier publish, trigger publish"

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get latest prettier release
              run: |
                TAG_NAME="$(curl -sL https://api.github.com/repos/prettier/prettier/releases/latest | jq -r ".tag_name")"
                echo "PRETTIER_TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
            - name: Get latest own release
              run: |
                TAG_NAME="$(curl -sL https://api.github.com/repos/Gitii/PackedPrettier/releases/latest | jq -r ".tag_name")"
                echo "TAG_NAME=${TAG_NAME#v}" >> $GITHUB_ENV
            - uses: rickstaa/action-create-tag@v1
              if: ${{ env.PRETTIER_TAG_NAME != env.TAG_NAME }}
              with:
                tag: "v${{ env.PRETTIER_TAG_NAME }}"
            - name: Create new release when there is a new prettier release
              uses: ./.github/actions/publish
              if: ${{ env.PRETTIER_TAG_NAME != env.TAG_NAME }}
              with:
                commit: ${{ github.event.head_commit.sha }}
                version: "${{ env.PRETTIER_TAG_NAME }}"
                build_number: "${{ github.run_number }}"
                nuget_api_key: "${{ secrets.NUGET_API_KEY }}"
