name: "On prettier publish, trigger publish"

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get latest prettier release
              run: echo "PRETTIER_TAG_NAME=v$(curl -sL https://api.github.com/repos/prettier/prettier/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV
            - name: Get latest own release
              run: echo "TAG_NAME=$(curl -sL https://api.github.com/repos/Gitii/PackedPrettier/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV
            - uses: rickstaa/action-create-tag@v1
              if: ${{ env.PRETTIER_TAG_NAME != env.TAG_NAME }}
              with:
                tag: "${{ env.PRETTIER_TAG_NAME }}"
            - name: Create new release when there is a new prettier release
              uses: ./.github/workflows/publish.yml
              if: ${{ env.PRETTIER_TAG_NAME != env.TAG_NAME }}
              with:
                commit: ${{ github.event.head_commit.sha }}
                version: "${{ env.PRETTIER_TAG_NAME }}"
