name: "Create release when there is a new prettier release"

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get latest prettier release
              run: echo "PRETTIER_TAG_NAME=$(curl -sL https://api.github.com/repos/prettier/prettier/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV
            - name: Get latest own release
              run: echo "TAG_NAME=$(curl -sL https://api.github.com/repos/Gitii/PackedPrettier/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV
            - name: Create new release when there is a new prettier release
              uses: rickstaa/action-create-tag@v1
              if: ${{ env.PRETTIER_TAG_NAME != env.TAG_NAME }}
              with:
                  tag: "v${{ env.PRETTIER_TAG_NAME }}"
                  message: "Update for new prettier release ${{ env.PRETTIER_TAG_NAME }}"
